### ISSUE TITLE
Clarifications on the package

### ISSUE THREAD

**Issue by abishekrsrikaanth** [taftse/camelot-auth#31]
- The account table on the migration does not have a `password` field, so how does the package validate the credentials when using the local driver? Is this something that we need to add ourselves?
- The default configuration has a model `CamelotUser` set. This does not exist on the package. Should this be changed too?
- Is it possible to know what is the currently loaded driver for the logged in user?

**Comment by taftse** [comment]
@abishekrsrikaanth thanks for pointing out that the create_local_account_table migration was missing i have now added it

default configuration model value in the config is currently not in use  the model is hard  coded but will be changeable in the next version

i don't currently have anything built in to detect what driver the user used to log-in as i have not had a user case for it to date but it should be easy enough to add,
maybe by setting the driver/provider in a session 

if you could give me a user case i might be able to add it to the next version

**Comment by abishekrsrikaanth** [comment]
Further to your answers on the clarifications, can you please clarify the following:
- There are 2 configuration files `camelot` and `localcamelot`. Why 2 files?
- With regards to clarification on a use case for knowing the driver/provider. Here is my use case.

```
Route::any('login/{provider?}/{callback?}',function(){
    try
    {
        Camelot::authenticate();

        if(Camelot::check()){
            echo 'Welcome'.Camelot::User()->first_name.' '.Camelot::User()->last_name.' you have been successfully logged in';
        }
    }
    catch(\Exception $e)
    {
            echo 'user could not be logged in';
    }
});
```

With the above code, how do I know which provider was currently used to authenticate when `Camelot::authenticate()` was called. I basically need to load the friends from the database based on what provider the user signed in through. If it was the facebook, then load the facebook users, if it was the twitter, then load the twitter friends.
- Would you show an example of how to use both the login and provider based signup/signin. The problem I am having is to understand how the data flows between the different tables on this package and how it needs to be setup, which I am not clear right now.

**Comment by taftse** [comment]
the camelot config file is for the main routing to the correct driver 
the localcamelot config is for the local (or form) driver 

the original idea was for camelot not to care how a user logged in but to create one single user account with multiple login capabilities as such all the tables reference the central Account table
i have uploaded a copy of the database design 
https://www.dropbox.com/s/8dt1r67ne8x3dlh/DB_structure.png

there are 3 ways to sign up 

1 new user clicks the signin with facebook/twitter/github etc which try's to log them in using oauth2/oauth1

2 new user fills in a registration form and clicks submit (this will contain username and password for local form login driver)

3 existing user wants to add a ouath signing method 
this user will be signed in using ether another oauth provider or using the local form login 
this user then clicks the login to facebook/twitter/etc and logs in using oauth 
because the user is already signed in camelot will just add the oauth details to the signed in user account

hope this clarifies it some more i am planning on adding/ updating the documentation in the new version of camelot

**Comment by abishekrsrikaanth** [comment]
Is there any additional coding required for **item no. 3**? Once i call `Camelot::authenticate()`, does it automatically take care of creating the user and associating with the existing user?

The database design that I see is different from that of what is there on the migration scripts. Can you clarify? Is that the design for future enhancements to this package?

Also can you please advice on what is the configuration right now that should be configured to enable the `Forms authentication` by default and how do i tell the package which model the package will use to authenticate?

**Comment by taftse** [comment]
there is no additional coding required for no. 3 camelot takes care of the registration 
only for local authentication you will need to manually create a user 

the database design i posted is indeed for the next version(s) of camelot 

most of the settings in the example config file are correct and should work out of the box 
you can't currently set what model the package uses but this will be available in the next version
